config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :tasks
    resources :memberships
  end

  resources :users

  root 'pages#index'

  get "/about" => "pages#about", as: :about
  get "/terms" => "pages#terms", as: :terms
  get "/faq" => "pages#faq", as: :faq

  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign-in' => 'authentication#new', as: :signin
  post '/sign-in' => 'authentication#create'
  get '/sign-out' => 'authentication#destroy', as: :signout

end

app/models/task.rb
class Task < ActiveRecord::Base

validates :description, presence: true
validate :due_date_cannot_be_in_the_past, on: :create


  def due_date_cannot_be_in_the_past
    if due_date.present? && due_date < Date.today
      errors.add(:due_date, "can't be in the past")
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  before_action do
    @project = Project.find(params[:project_id])
  end

  # GET /tasks
  # GET /tasks.json
  def index

    @tasks = Task.where(complete: false).page(params[:page]).per(5)
    @ref = "incomplete"

    if params[:type] =="all"
      @tasks = Task.all.page(params[:page]).per(5)
      @ref = "all"

      # @tasks = Post.order(:created_at)
      respond_to do |format|
        format.html
        format.csv { send_data @tasks.as_csv }
      end



      # @tasks = Task.order("Description").page(params[:page]).per(5)
    end

  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to [@project, @task], notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def task_params
    params.require(:task).permit(:description, :complete, :due_date)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<div class= "form-horizontal">
  <%= form_for([@project, @task]) do |f| %>
  <div class= "form-group">
  <% if @task.errors.any? %>
    <div class= "col-sm-offset-1 col-sm-6 alert alert-danger">
      <h3><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h3>
        <ul>
          <% @task.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </div>
  </div>
  <% end %>


  <div class="form-group">
    <%= f.label :description, class: "col-sm-1 control-label" %>
      <div class="col-sm-4">
        <%= f.text_field :description, class: "form-control" %>
      </div>
  </div>


  <div class="form-group">
      <%= f.label :due_date, class: "col-sm-1 control-label" %>
      <div class="col-sm-2">
          <%= f.date_field :due_date, class: "form-control" %>

      </div>
  </div>

  <% if @task.persisted? %>
    <div class="form-group">
      <div class="col-sm-offset-1 col-sm-10">
        <div class= "checkbox">
          <label>
            <%= f.check_box :complete %> Complete
          </label>
        </div>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-sm-offset-1 col-sm-10"> <br>
      <%= f.submit name: button_name, class: "btn btn-primary"%>
    </div>
  </div>

  <br>
    <% end %>
</div>

app/views/tasks/edit.html.erb
<div class="Edit">

  <ol class="breadcrumb">
    <li><a><%= link_to "Tasks", tasks_path %> </a></li>
    <li><a><%= link_to @task.description %></a></li>
    <li class= "active">Edit</li>
  </ol>

  <h1>Editing task</h1>

  <%= render 'form', button_name: "Update Task" %>

  <br>
  <br>
  <br>
  <br>
  <br>
</div>

app/views/tasks/index.html.erb
<div class= "page-header">
  <div class= "pull-right">
    <%=link_to_if((@ref == "incomplete"), "All", project_tasks_path(@project, type:"all")) %> |
    <%=link_to_if((@ref == "all"), "Incomplete", project_tasks_path(@project, type:"incomplete")) %>
    <%= link_to 'Create Task', new_project_task_path(@project), class:"btn btn-primary" %>
  </div>

  <h1>Tasks</h1>
</div>

<table class = "table">
  <thead>
    <tr>
      <th>Description</th>
      <th>Complete</th>
      <th>Due</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.description %></td>
        <td><%= task.complete %></td>
        <td>
          <% if task.due_date %>
          <%= task.due_date.strftime("%m/%d/%Y") %>
          <% else nil %>
          <%end%>
        </td>
          <td>
            <div class= "pull-right">
              <%= link_to 'Show', [@project, task], class:"btn btn-success" %>
              <%= link_to 'Edit', edit_project_task_path(@project, task), class:"btn btn-info" %>
              <%= link_to 'Destroy', [@project,task], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %>
            </div>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @tasks %>

<br>

app/views/tasks/new.html.erb
<div class= "new_task">

  <ol class="breadcrumb">
    <li><a><%= link_to "Tasks", project_tasks_path(@project) %> </a></li>
    <li class="active"> New Task</li>
  </ol>

  <h1>New Task</h1>

  <%= render 'form', button_name: "Create Task" %>

</div>

app/views/tasks/show.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'Edit', edit_project_task_path(@project, @task), class: "btn btn-info" %>
  </div>
  <h1><%= @task.description %></h1>
</div>

<ol class="breadcrumb">
  <li><%= link_to "Tasks", project_tasks_path(@project) %></li>
  <li class= "active"> <%= @task.description %></li>
</ol>

<p>
  <strong>Complete:</strong>
  <%= @task.complete %>
</p>

<p>
  <strong>Due Date:</strong>
  <% if @task.due_date %>
  <%= @task.due_date.strftime("%m/%d/%Y") %>
  <% else nil %>
  <%end%>
</p>