config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :tasks
    resources :memberships
  end

  resources :users

  root 'pages#index'

  get "/about" => "pages#about", as: :about
  get "/terms" => "pages#terms", as: :terms
  get "/faq" => "pages#faq", as: :faq

  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign-in' => 'authentication#new', as: :signin
  post '/sign-in' => 'authentication#create'
  get '/sign-out' => 'authentication#destroy', as: :signout

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  has_secure_password

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
  end

  def show
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def update
      @user.update(user_params)
      if @user.save
        redirect_to users_path, notice: 'User was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, notice: 'User was successfully deleted.'
  end

private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/views/users/edit.html.erb
<div class="page-header">
  <h1>Edit User</h1>
</div>

<div class= "form-horizontal">
    <%= form_for(@user) do |f| %>
      <div class= "form-group">
        <% if @user.errors.any? %>
        <div class= "col-sm-offset-2 col-sm-6 alert alert-danger">
          <h3><%= pluralize(@user.errors.count, "error") %> prohibited this task from being saved:</h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  <div class="form-group">
    <%= f.label :first_name, "First Name", class: "col-sm-2 control-label" %>
      <div class="col-sm-4">
        <%= f.text_field :first_name, class: "form-control" %>
      </div>
  </div>

  <div class="form-group">
    <%= f.label :last_name, "Last Name", class: "col-sm-2 control-label" %>
      <div class="col-sm-4">
        <%= f.text_field :last_name, class: "form-control" %>
      </div>
  </div>


  <div class="form-group">
      <%= f.label :email, class: "col-sm-2 control-label" %>
      <div class="col-sm-4">
          <%= f.email_field :email, class: "form-control" %>
      </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-4"> <br>
      <%= f.submit button_name:"Update User", class: "btn btn-primary" %>
    </div>
  </div>
  <%end%>
  <div class=" col-sm-offset-2 col-sm-4 well well-lg text-center">
    <%= link_to 'Delete User', user_path(@user), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  </div>
</div>

app/views/users/index.html.erb
<div class= "page-header">
  <div class= "pull-right">
    <%= link_to 'Create User', new_user_path, class:"btn btn-primary" %>
  </div>

  <h1>Users</h1>
</div>


<table class = "table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to ("#{user.first_name} #{user.last_name}"), user_path(user) %> </td>
        <td><%= mail_to(user.email) %></td>
        <td>
          <div class= "pull-right">
            <%= link_to 'Edit', edit_user_path(user), class:"btn btn-info" %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<div class="page-header">
  <h1>New User</h1>
</div>

<div class= "form-horizontal">
  <%= form_for(@user) do |f| %>
<div class= "form-group">
<% if @user.errors.any? %>
  <div class= "col-sm-offset-2 col-sm-6 alert-danger">
    <h3><%= pluralize(@user.errors.count, "error") %> prohibited this task from being saved:</h3>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  </div>
</div>
<% end %>

  <div class="form-group">
    <%= f.label :first_name, "First Name", class: "col-sm-2 control-label" %>
      <div class="col-sm-5">
        <%= f.text_field :first_name, class: "form-control" %>
      </div>
  </div>

  <div class="form-group">
    <%= f.label :last_name, "Last Name", class: "col-sm-2 control-label" %>
      <div class="col-sm-5">
        <%= f.text_field :last_name, class: "form-control" %>
      </div>
  </div>


  <div class="form-group">
      <%= f.label :email, class: "col-sm-2 control-label" %>
      <div class="col-sm-5">
          <%= f.email_field :email, class: "form-control" %>
      </div>
  </div>

  <div class ="form-group">
    <%= f.label :password, class: "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>

  <div class ="form-group">
    <%= f.label :password_confirmation, "Password Confirmation", class: "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
  </div>


  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-5"> <br>
      <%= f.submit button_name:"Create User", class: "btn btn-primary" %>
    </div>
  </div>
  <%end%>
</div>

app/views/users/show.html.erb
<p>
<strong> First Name:</strong>
  <%= @user.first_name %>
</p>

<p>
<strong>Last Name:</strong>
  <%= @user.last_name %>
</p>

<p>
<strong>Email:</strong>
  <%= mail_to(@user.email) %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> 