config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :tasks
    resources :memberships
  end

  resources :users

  root 'pages#index'

  get "/about" => "pages#about", as: :about
  get "/terms" => "pages#terms", as: :terms
  get "/faq" => "pages#faq", as: :faq

  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign-in' => 'authentication#new', as: :signin
  post '/sign-in' => 'authentication#create'
  get '/sign-out' => 'authentication#destroy', as: :signout

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true

  has_many :tasks
  has_many :memberships
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
    end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to project_path(@project), notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @project.update(project_params)
    if @project.save
      redirect_to project_path, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path, notice: 'Project was successfully deleted.'
  end

private

  def set_project
    @project = Project.find(params[:id])
  end

def project_params
    params.require(:project).permit(:name)
end

end

app/views/projects/edit.html.erb
<div class="page-header">
  <h1>Edit Project</h1>
</div>

<div class= "form-horizontal">
  <%= form_for(@project) do |f| %>
  <div class= "form-group">
  <% if @project.errors.any? %>
    <div class= "col-sm-offset-2 col-sm-6 alert alert-danger">
      <h3><%= pluralize(@project.errors.count, "error") %> prohibited this task from being saved:</h3>
        <ul>
          <% @project.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </div>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "Name", class: "col-sm-2 control-label" %>
      <div class="col-sm-4">
        <%= f.text_field :name, class: "form-control" %>
      </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-4"> <br>
      <%= f.submit button_name:"Update Project", class: "btn btn-primary" %>
    </div>
  </div>
  <%end%>
</div>

app/views/projects/index.html.erb
<div class= "page-header">
  <div class= "pull-right">
    <%= link_to 'New Project', new_project_path, class:"btn btn-primary" %>
  </div>

  <h1>Projects</h1>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Tasks</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project_path(project) %></td>
        <td><%= project.tasks.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<div class="page-header">
  <h1>Create Project</h1>
</div>

<div class= "form-horizontal">
  <%= form_for(@project) do |f| %>
  <div class= "form-group">
  <% if @project.errors.any? %>
    <div class= "col-sm-offset-2 col-sm-6 alert alert-danger">
      <h3><%= pluralize(@project.errors.count, "error") %> prohibited this task from being saved:</h3>
        <ul>
          <% @project.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </div>
  </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name, "Name", class: "col-sm-2 control-label" %>
      <div class="col-sm-4">
        <%= f.text_field :name, class: "form-control" %>
      </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-4"> <br>
      <%= f.submit button_name:"Create Project", class: "btn btn-primary" %>
    </div>
  </div>
  <%end%>
</div>

app/views/projects/show.html.erb
<div class= "page-header">
  <div class= "pull-right">
    <%= link_to 'Edit', edit_project_path(@project), class: "btn btn-info" %>
    <%= link_to 'Delete', project_path(@project), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  </div>
  <h1><%= @project.name %></h1>
</div>

<p>
  <%= link_to pluralize(@project.tasks.count, 'Task'), project_tasks_path(@project) %>
</p>

<p>
  <%= link_to pluralize(@project.memberships.count, "Member"), project_memberships_path(@project) %>
</p>