config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :tasks
    resources :memberships
  end

  resources :users

  root 'pages#index'

  get "/about" => "pages#about", as: :about
  get "/terms" => "pages#terms", as: :terms
  get "/faq" => "pages#faq", as: :faq

  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign-in' => 'authentication#new', as: :signin
  post '/sign-in' => 'authentication#create'
  get '/sign-out' => 'authentication#destroy', as: :signout

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../favicon.ico">

  <title>gCamp</title>

  <%= stylesheet_link_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'application' %>

  <!-- Bootstrap core CSS -->
  <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="jumbotron.css" rel="stylesheet">

  <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
  <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
  <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body>

  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">gCamp</a>
      </div>
      <ul class= "nav navbar-nav navbar-right">
        <% if current_user %>
        <li><%= link_to ("#{current_user.first_name} #{current_user.last_name}"), user_path(current_user) %></li>
        <li><%= link_to "Sign Out", signout_path %></li>
        <% else %>
        <li><%= link_to "Sign Up", signup_path %></li>
        <li><%= link_to "Sign In", signin_path %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="container">

    <% if notice %>
    <p id="notice"><%= notice %></p>
    <% end %>

    <%= yield %>
    <hr>

    <div class ="footer">
      <footer>
        <div class="row">
          <div class= "col-md-5">
            <%= link_to "About |", about_path %> <%= link_to "Terms |", terms_path%> <%= link_to "FAQ |", faq_path %> <%= link_to "Users |", users_path %> <%= link_to "Projects", projects_path %>
          </div>

          <div class= "col-md-offset-9">
            <%= link_to "https://www.linkedin.com" do %>
            <%= image_tag("linked_in.jpg") %>
            <%end%> |

            <%= link_to "https://github.com/" do %>
            <%= image_tag("GitHub.png") %>
            <%end%> |

            <%= link_to "https://twitter.com/" do %>
            <%= image_tag("Twitter.png") %>
            <%end%> |

            <%= link_to "http://www.galvanize.it/school/" do %>
            <%= image_tag("gschool.png") %>
            <%end%>
          </div>
        </div>
      </footer>
    </div>

  </div>

</div> <!-- /container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>